import streamlit as st
import pandas as pd
import requests
from datetime import date, timedelta, datetime
import plotly.express as px
import pytz

# --- Configuration ---
st.set_page_config(page_title="Iberian Energy Prices", page_icon="⚡", layout="wide")

# --- 🔗 URL PARAMETER HANDLING ---
qp = st.query_params

def get_param(key, default_val, type_func):
    try:
        if key in qp:
            return type_func(qp[key])
        return default_val
    except:
        return default_val

# Defaults
default_lang_idx = get_param("lang_idx", 2, int)
default_vat = get_param("vat", 23.0, float)
default_comm_fee = get_param("comm_fee", 0.025, float)
default_grid_type = get_param("grid_type", "Fixed", str)
default_grid_fixed = get_param("grid_fixed", 0.060, float)
default_grid_p1 = get_param("grid_p1", 0.100, float)
default_grid_p2 = get_param("grid_p2", 0.040, float)
default_grid_p3 = get_param("grid_p3", 0.010, float)
default_show_fixed_comp = get_param("show_fixed_comp", False, lambda x: x.lower() == 'true')
default_fixed_val = get_param("fixed_val", 0.120, float)

# --- 🌍 TRANSLATION ENGINE ---
LANGUAGES = {
    "English": {
        "title": "⚡ Iberian Electricity Prices",
        "config_title": "⚙️ Configuration & Tariff",
        "tab_daily": "📅 Daily View",
        "tab_history": "📈 30-Day Trend",
        "select_date": "Select Date",
        "country": "Country",
        "settings": "Settings",
        "show_raw": "Show Raw Market Price (€/MWh)",
        "comp_toggle": "Compare with Fixed Rate",
        "fixed_input": "Your Fixed Energy Price (€/kWh)",
        "taxes": "Taxes & Fees",
        "vat": "VAT / IVA (%)",
        "comm_fee_label": "Commercial Margin (€/kWh)",
        "comm_help": "Fee charged by your retailer to manage the contract. Usually 0.01 - 0.03 €.",
        "grid_fee_label": "Grid Access Fees",
        "grid_help": "Cost to maintain cables and transport energy. Can be fixed or variable.",
        "grid_type_fixed": "Fixed",
        "grid_type_var": "Variable (Time-of-Use)",
        "grid_fixed_input": "Fixed Grid Fee (€/kWh)",
        "grid_p1_input": "Peak Fee (Punta) (€/kWh)",
        "grid_p2_input": "Standard Fee (Llano) (€/kWh)",
        "grid_p3_input": "Off-Peak Fee (Valle) (€/kWh)",
        "calc_title": "⏱️ Plan Your Usage",
        "calc_appliance": "Select Appliance",
        "calc_custom": "Custom Power...",
        "calc_power": "Power (Watts)",
        "calc_duration": "Duration (Hours)",
        "calc_cost": "Estimated Cost",
        "calc_start": "Best Start:",
        "view_table": "View Detailed Data Table",
        "table_title": "📋 Hourly Data",
        "download_csv": "📥 Download Data as CSV",
        "daily_summary": "Daily Summary",
        "avg_price": "Average Price",
        "min_price": "Lowest Price",
        "max_price": "Highest Price",
        "your_rate": "Your Fixed Rate",
        "tax_applied": "Tax Applied",
        "price_axis": "Price",
        "hour_axis": "Start Hour",
        "interval_col": "Time Interval",
        "price_col": "Price",
        "base_col": "Base Market Price",
        "date_axis": "Date",
        "now_label": "NOW",
        "verdict_good": "✅ Great time to use energy!",
        "verdict_bad": "❌ Expensive! Wait if possible.",
        "verdict_avg": "⚖️ Average Price.",
        "verdict_fixed_win": "✅ Cheaper than your Fixed Rate!",
        "verdict_fixed_loss": "❌ More expensive than Fixed Rate.",
        "zone_valle": "Off-Peak",
        "zone_llano": "Standard",
        "zone_punta": "Peak",
        "data_unavailable": "⚠️ Data not available for",
        "raw_info": "Showing raw market data in €/MWh. Taxes and tariffs are hidden.",
        "hist_title": "Price Evolution (Last 30 Days)",
        "hist_avg_note": "Showing daily average prices.",
        "explain_title": "📝 Price Breakdown",
        "explain_formula": "Calculation Formula",
        "explain_market": "Market Price",
        "explain_comm": "Comm. Margin",
        "explain_grid": "Grid Fees",
        "explain_tax": "VAT"
    },
    "Español": {
        "title": "⚡ Precio de la Luz (OMIE)",
        "config_title": "⚙️ Configuración y Tarifa",
        "tab_daily": "📅 Vista Diaria",
        "tab_history": "📈 Tendencia 30 Días",
        "select_date": "Seleccionar Fecha",
        "country": "País",
        "settings": "Configuración",
        "show_raw": "Ver Precio Mercado (€/MWh)",
        "comp_toggle": "Comparar con Tarifa Fija",
        "fixed_input": "Precio Energía Fijo (€/kWh)",
        "taxes": "Impuestos y Peajes",
        "vat": "IVA (%)",
        "comm_fee_label": "Margen Comercial (€/kWh)",
        "comm_help": "Coste de gestión de la comercializadora. Suele ser 0.01 - 0.03 €.",
        "grid_fee_label": "Peajes de Acceso",
        "grid_help": "Coste de redes y transporte. Puede ser fijo o variable.",
        "grid_type_fixed": "Fijo",
        "grid_type_var": "Variable (Horario)",
        "grid_fixed_input": "Peaje Fijo (€/kWh)",
        "grid_p1_input": "Peaje Punta (P1) (€/kWh)",
        "grid_p2_input": "Peaje Llano (P2) (€/kWh)",
        "grid_p3_input": "Peaje Valle (P3) (€/kWh)",
        "calc_title": "⏱️ Planificador de Consumo",
        "calc_appliance": "Elegir Electrodoméstico",
        "calc_custom": "Potencia Personalizada...",
        "calc_power": "Potencia (W)",
        "calc_duration": "Duración (Horas)",
        "calc_cost": "Coste Estimado",
        "calc_start": "Mejor Hora:",
        "view_table": "Ver Tabla de Datos",
        "table_title": "📋 Datos Horarios",
        "download_csv": "📥 Descargar CSV",
        "daily_summary": "Resumen Diario",
        "avg_price": "Precio Medio",
        "min_price": "Mínimo",
        "max_price": "Máximo",
        "your_rate": "Tu Tarifa Fija",
        "tax_applied": "Impuesto Aplicado",
        "price_axis": "Precio",
        "hour_axis": "Hora Inicio",
        "interval_col": "Intervalo Horario",
        "price_col": "Precio",
        "base_col": "Precio Base Mercado",
        "date_axis": "Fecha",
        "now_label": "AHORA",
        "verdict_good": "✅ ¡Buen momento!",
        "verdict_bad": "❌ Caro. Espera si puedes.",
        "verdict_avg": "⚖️ Precio Normal.",
        "verdict_fixed_win": "✅ ¡Más barato que tu Fija!",
        "verdict_fixed_loss": "❌ Más caro que tu Fija.",
        "zone_valle": "Valle",
        "zone_llano": "Llano",
        "zone_punta": "Punta",
        "data_unavailable": "⚠️ Datos no disponibles para",
        "raw_info": "Mostrando datos crudos en €/MWh. Sin impuestos ni peajes.",
        "hist_title": "Evolución de Precios (Últimos 30 Días)",
        "hist_avg_note": "Mostrando precios medios diarios.",
        "explain_title": "📝 Desglose del Precio",
        "explain_formula": "Fórmula de Cálculo",
        "explain_market": "Precio Mercado",
        "explain_comm": "Margen Comer.",
        "explain_grid": "Peajes",
        "explain_tax": "IVA"
    },
    "Português": {
        "title": "⚡ Preço da Eletricidade (OMIE)",
        "config_title": "⚙️ Configuração e Tarifa",
        "tab_daily": "📅 Visão Diária",
        "tab_history": "📈 Tendência 30 Dias",
        "select_date": "Selecionar Data",
        "country": "País",
        "settings": "Configurações",
        "show_raw": "Ver Preço de Mercado (€/MWh)",
        "comp_toggle": "Comparar com Taxa Fixa",
        "fixed_input": "Seu Preço Fixo (€/kWh)",
        "taxes": "Impostos e Taxas",
        "vat": "IVA (%)",
        "comm_fee_label": "Margem Comercial (€/kWh)",
        "comm_help": "Custo de gestão do comercializador. Geralmente 0.01 - 0.03 €.",
        "grid_fee_label": "Tarifas de Acesso às Redes",
        "grid_help": "Custo de transporte e manutenção da rede. Pode ser fixo ou variável.",
        "grid_type_fixed": "Fixo",
        "grid_type_var": "Variável (Horário)",
        "grid_fixed_input": "Acesso Fixo (€/kWh)",
        "grid_p1_input": "Taxa Ponta (P1) (€/kWh)",
        "grid_p2_input": "Taxa Cheias (P2) (€/kWh)",
        "grid_p3_input": "Taxa Vazio (P3) (€/kWh)",
        "calc_title": "⏱️ Planear Consumo",
        "calc_appliance": "Escolher Eletrodoméstico",
        "calc_custom": "Potência Personalizada...",
        "calc_power": "Potência (W)",
        "calc_duration": "Duração (Horas)",
        "calc_cost": "Custo Estimado",
        "calc_start": "Melhor Início:",
        "view_table": "Ver Tabela de Dados",
        "table_title": "📋 Dados Horários",
        "download_csv": "📥 Baixar CSV",
        "daily_summary": "Resumo Diário",
        "avg_price": "Preço Médio",
        "min_price": "Mínimo",
        "max_price": "Máximo",
        "your_rate": "Sua Taxa Fixa",
        "price_axis": "Preço",
        "hour_axis": "Hora Início",
        "date_axis": "Data",
        "interval_col": "Intervalo Horário",
        "price_col": "Preço",
        "base_col": "Preço Base Mercado",
        "now_label": "AGORA",
        "verdict_good": "✅ Bom momento!",
        "verdict_bad": "❌ Caro. Espere se puder.",
        "verdict_avg": "⚖️ Preço Médio.",
        "verdict_fixed_win": "✅ Mais barato que a Fixa!",
        "verdict_fixed_loss": "❌ Mais caro que a Fixa.",
        "zone_valle": "Vazio",
        "zone_llano": "Cheias",
        "zone_punta": "Ponta",
        "data_unavailable": "⚠️ Dados não disponíveis para",
        "raw_info": "Mostrando dados brutos em €/MWh. Sem impostos ou taxas.",
        "hist_title": "Evolução de Preços (Últimos 30 Dias)",
        "hist_avg_note": "Mostrando preços médios diários.",
        "explain_title": "📝 Composição do Preço",
        "
